style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/bojand/ghz
options:
  commits:
    filters:
      Type:
        - docs
        - enhance
        - feat
        - fix
        - build
  commit_groups:
    title_maps:
      docs: Documentation
      enhance: Enhancements
      feat: Features
      fix: Bug Fixes
      build: Build
  header:
    pattern: "^(\\w*)?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE